//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping
    {
        public int ShoppingID { get; set; }
        public string ShoppingName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }
}
